### ISSUE TITLE
Please consider making a release

### ISSUE THREAD

**Issue by yurivict** [TA-Lib/ta-lib#15]
RC was started in 2016 and the release never came.

**Comment by mario4tier** [comment]
For many years I was hoping that someone younger would step up and take over TA-Lib (I am not immortal), but obviously this has not yet happen.

What can be done?
=================
I see that you are a FreeBSD maintainer. I am not knowledgeable about the latest best-practice to release a good portable C++ library. If you can point me to a good open-source example to follow... then I can try to do the same for TA-Lib for (tentatively) sometime in 2025.

**Comment by mario4tier** [comment]
This is now resolved with release 0.6.1

CMake and autotools have been updated for best-practice.

All packaging are now done automatically by Github actions.

Hopefully, TA-Lib is now modern and easy enough for others to step and be able to "trig" new release.

Thanks.
