### ISSUE TITLE
Broken for directory paths with spaces

### ISSUE THREAD

**Issue by mrjbq7** [TA-Lib/ta-lib#2]
Build errors like this:

```
libtool: link: (cd .libs/libta_lib.lax/libta_abstract.a && ar x "/Users/trentbrooks/Downloads/ta-lib 3/src/ta_abstract/.libs/libta_abstract.a")
../libtool: line 1717: cd: .libs/libta_lib.lax/libta_abstract.a: No such file or directory
make[2]: *** [libta_lib.la] Error 1
make[1]: *** [all-recursive] Error 1
make: *** [all-recursive] Error 1
```

If ``make`` run in a path that includes spaces.

https://github.com/mrjbq7/ta-lib/issues/190

Maybe it's worth starting to fix more of these build problems and forking from SF... dunno.

**Comment by mario4tier** [comment]
I will proceed to deprecate SF and refer to here as the official version for TA-Lib.

**Comment by mario4tier** [comment]
Please try again with latest 0.6.1 release. There was a lot of CMake/autotools fixes.
