### ISSUE TITLE
Release v0.5 (or v0.4.1) with the small values fix

### ISSUE THREAD

**Issue by iliazeus** [TA-Lib/ta-lib#31]
https://github.com/TA-Lib/ta-lib/commit/4d0f2718ceb0bc1e6810557fb8cff1ff84503213

This fix is in the code since 2009. I see a lot of people (including my team) stumbling into issues when using indicators for small numbers. [This issue](https://github.com/TA-Lib/ta-lib-python/issues/594) has a long list of other issues about the same problem, for example.

**Comment by mario4tier** [comment]
Thanks. This issue is now resolved in 0.6.1 release
