### ISSUE TITLE
Excel version

### ISSUE THREAD

**Issue by huwawilliams** [TA-Lib/ta-lib#36]
Hi,

Can anyone please advise if there's still an Excel version of this available, or a recommended method of working via Excel?

**Comment by mario4tier** [comment]
The original excel plugin is no longer available. It was written with older Microsoft add-ins tricks that no longer works.

To work with excel again, one would need to "glue" TA-Lib with latest ways to do Office add-ins:
https://learn.microsoft.com/en-us/office/dev/add-ins/develop/develop-overview

(It is very feasible to be done by most qualified software engineer... but I have no time or motivation to work on this personally)

**Comment by huwawilliams** [comment]
Ok, thanks for your reply.
