### ISSUE TITLE
Release Windows 64-bit Build

### ISSUE THREAD

**Issue by mrjbq7** [TA-Lib/ta-lib#43]
Probably the most immediately useful thing we could do is release a TA-Lib binary for Windows, built for 64-bit.

Seems to keep tripping people up, and nobody reads the README.

Instructions are here:

https://github.com/ta-lib/ta-lib-python?tab=readme-ov-file#windows

**Comment by mario4tier** [comment]
@mrjbq7 first release candidates are ready.

It is ```dist/ta-lib-0.6.0-win64.zip``` and ```dist/ta-lib-0.6.0-src.tar.gz```

Do not change yet the installation procedure for your users. More automation work on my side to do... and 'dist' will always contain only the release candidate. The released binaries will instead be tag Github assets.

In meantime, it would be great help for you to early test these. Particularly for windows which I have not tested at all.

## Another thing, if you have time...
Automation will be done with python and Github actions.

Have a peek at scripts/test-disp.py and scripts/install_tests/python.py, the intent is to verify the **ta-lib-python installation steps** using the release candidate.

Don't bother for the github action, I am doing these... but you can help greatly by coding your installation steps in install_tests/python.py... and call test-disp.py directly to simulate what the CI will do later.

**Comment by mario4tier** [comment]
If you make changes, please do it directly in the 'dev' branch (no PR needed). Might want to do a dummy push to verify if there is any permission issues...

As you work on the dev branch do ``~/scripts/sync.py``` once in a while. This should help keeping your local dev up-to-date and less probable to have big merge issues later.

**Comment by mario4tier** [comment]
@mrjbq7 Question for python. On Linux the ta-lib_0.6.0_amd64.deb will install the library under /usr/lib. When the user instead build from source (either ./configure or cmake) it will install by default under /usr/local. I think this is "best practice", but wondering... can Python find ta-lib at both location? (and when present at both place, which one is selected?)

(FYI, on windows the .msi and a setup.exe will be CI generated using CMake\CPack. My goal is to always install in C:\Program Files\TA-Lib regardless of the installation method).

**Comment by mrjbq7** [comment]
Right now we look through some well known locations, and also allow the user to pass an environment variable if it is installed somewhere else:

https://github.com/TA-Lib/ta-lib-python/blob/cef4c0c55f0e76fc8546f8b1128ab9328c0c1c33/setup.py#L35

Long term we need to probably static link the TA-Lib C library because windows users aren’t well served by their OS.

**Comment by mario4tier** [comment]
@mrjbq7 Almost done with CI, so should be able to "trig" a release sometimes this week.

So far, it is working great: devs just push code changes... github tests and packages for everything.

Left to be done:
  - Automate PR to [homebrew/core](https://github.com/Homebrew/homebrew-core)
  - Documentation

====

In meantime, I did a "practice run" of the automated release on a fork. Telling you in case you would want an early peek to "spot" problems (the assets are very likely to be the same for the official release):
  https://github.com/TA-Lib/ta-lib-temp/releases/tag/v0.6.0

**Comment by mario4tier** [comment]
@mrjbq7 Release 0.6.1 done

Check the [release notes](https://github.com/TA-Lib/ta-lib/releases) for breaking changes to static/shared lib names and includes location.

BTW, CI for brew is now also done : https://formulae.brew.sh/formula/ta-lib

**Comment by mario4tier** [comment]
**Static Lib locations**

x86 64-bits:  C:\Program Files\TA-Lib\lib\ta-lib-static.lib
x86 32-bits:  C:\Program Files (x86)\TA-Lib\lib\ta-lib-static.lib

You will also find headers and DLL at same location.

With the .msi, it is now very easy to install/uninstall on windows:
![image](https://github.com/user-attachments/assets/56e29c4d-ffc7-445e-9335-f907efe6f32d)
