### ISSUE TITLE
Is TA-Lib thread-safe when used in a multithreaded environment?

### ISSUE THREAD

**Issue by gitctrlx** [TA-Lib/ta-lib#49]
Hello TA-Lib team,

Thank you for maintaining and providing this excellent library for technical analysis. I have a question regarding TA-Lib's thread safety, particularly when used in a multithreaded environment.

Background:

From my understanding of the source code, functions like TA_Initialize, TA_SetCandleSettings, and TA_Shutdown modify or rely on the global variable TA_Globals. This raises concerns about potential data races when multiple threads access these functions concurrently.

My Questions:

1. Is TA-Lib designed to be thread-safe?

For example, if multiple threads independently call functions like TA_SMA or TA_EMA with their own input/output buffers, will there be any thread safety issues?

2. Are the global initialization functions (TA_Initialize/TA_Shutdown) thread-safe?

Should these functions only be called once in a single-threaded context to avoid conflicts?

3. Does TA-Lib have any specific guidelines or best practices for multithreaded usage?

For instance, should users manually lock around calls that involve shared resources?

Why It Matters:

With modern systems heavily relying on multithreading to improve performance, it's important to clarify whether TA-Lib's current design can handle concurrent calls or if developers need to implement synchronization mechanisms (e.g., mutexes) on their end.

Thank you for taking the time to address this question. I believe this information will greatly benefit developers who integrate TA-Lib into multi-threaded systems.

Looking forward to your response!

**Comment by mario4tier** [comment]
@gitctrlx Thanks, these are good questions and it shows that you have experience with the potential issues :smile: 

To answer, I added a section to the docs, let me know if you see something missing:
  https://ta-lib.org/api/#Multithreading

(Stay tune for the rest of the docs be significantly updated in early 2025... right after we release a "modernize" 0.6.0 packaging by end-of-year).
