### ISSUE TITLE
Clarification on TA_GLOBALS_UNSTABLE_PERIOD(TA_FUNC_UNST_EMA, Ema) Unstable Period in EMA Calculation

### ISSUE THREAD

**Issue by gitctrlx** [TA-Lib/ta-lib#50]
#### Description:
I am reviewing the implementation of the EMA (Exponential Moving Average) function in your code and came across the following line in the `TA_EMA_Lookback` function:

```c
return optInTimePeriod - 1 + TA_GLOBALS_UNSTABLE_PERIOD(TA_FUNC_UNST_EMA, Ema);
```

I would like to understand more about the purpose and effect of `TA_GLOBALS_UNSTABLE_PERIOD(TA_FUNC_UNST_EMA, Ema)` in this calculation. Specifically:

1. **What is the purpose of the "unstable period" introduced by this macro?**  
   Is it meant to account for initialization in the EMA calculation? If so, could you clarify what this unstable period is doing in the context of the EMA and how it affects the first few periods of the calculation?

2. **Is this unstable period necessary in all cases?**  
   In certain use cases where there is sufficient historical data (or in situations where we do not need to account for the initialization phase), can this part of the code be safely removed without impacting the stability or accuracy of the EMA computation?

3. **Does removing or modifying the unstable period affect the quality of the result?**  
   What would be the expected impact on the accuracy of the EMA if this adjustment was removed or modified, especially in real-time trading systems where immediate responses are important?

#### Additional Context:
I understand that some technical indicators like EMA require a "warm-up" period or initialization phase due to their recursive nature, but I would appreciate further clarification on this specific implementation. If possible, could you provide any references or reasoning behind the design choice of including this specific unstable period in the EMA calculation?

#### Request for Guidance:
Could you provide a more detailed explanation of when and why this unstable period is used, and whether removing it could lead to issues in the calculation accuracy or stability?

---

Thank you for your time and support!

**Comment by mario4tier** [comment]
@gitctrlx In short, it allows the library user to control having a "warm-up" period or not.

A design decision of TA-Lib is that, by setting the "warm-up" period of EMA you are also affecting all other TA-Lib functions using EMA in its algo. 

Therefore, it is important to include the "warm-up" in the lookback logic to keep things consistent. As an example the lookback for TA_MACD uses the EMA lookback:

   return   LOOKBACK_CALL(EMA)( optInSlowPeriod   )
          + LOOKBACK_CALL(EMA)( optInSignalPeriod );
