### ISSUE TITLE
Unable to build v.0.5.0 with configure

### ISSUE THREAD

**Issue by sjdhanasekaran** [TA-Lib/ta-lib#8]
https://github.com/TA-Lib/ta-lib/archive/refs/tags/v0.5.0.tar.gz

unable to build above release. With same way that how we compiled v.0.4.0 
./configure --prefix=/usr

and how explicitly force to compile with g++ instead gcc ?

kindly add readme

**Comment by khiemdoan** [comment]
I had same issue with you and this is my solution for Debian, Ubuntu:

```bash
sudo apt install automake gcc libtool make
wget -O ta-lib-0.5.0.tar.gz https://github.com/TA-Lib/ta-lib/archive/refs/tags/v0.5.0.tar.gz
tar -xzf ta-lib-0.5.0.tar.gz
cd ta-lib-0.5.0
sh autogen.sh
./configure --prefix=/usr
sudo make install
```

Hope this helps you 😸 😺

**Comment by mario4tier** [comment]
0.6.1 is now release with "modernize" autotools.

Hopefully, it will work better for your setup.

**Comment by sjdhanasekaran** [comment]
@mario4tier will try 0.6.1 thanks..!!

@khiemdoan Thanks
